### ISSUE TITLE
Error in obtaining the PlpData with the getPlpData() function:

### ISSUE THREAD

**Issue by malihamashkoor123** [OHDSI/PatientLevelPrediction#463]
I am trying to obtain the cohort covariates with the createCohortCovariateSettings() function from the PatientLevelPrediction package. However, I am running into the following error when I execute the getPlpData() function:

![Capture1](https://github.com/OHDSI/PatientLevelPrediction/assets/81391242/fa31118d-5ee8-47eb-a09b-195e5951be43)

The code that I am using to obtain the plpData is as follow:
 
![image](https://github.com/OHDSI/PatientLevelPrediction/assets/81391242/d1fb8bba-94cc-4cb0-b061-b4348b64cd31)

I am supplying the covaraiteSettings as a list of default covariates and cohort covariates obtained by the functions createCovariateSettings() and createCohortCovariateSettings(), in the following way:
 
![image](https://github.com/OHDSI/PatientLevelPrediction/assets/81391242/6820b1eb-68e4-4ea7-8abe-8b6b574264f5)

Additionally, on the other hand if I provide the covaraiteSettings in the following way:
 
![image](https://github.com/OHDSI/PatientLevelPrediction/assets/81391242/6428158b-c61c-43aa-a963-9eee8c39293b)

Then the code is hanging:
 
![image](https://github.com/OHDSI/PatientLevelPrediction/assets/81391242/bb739c2b-7109-40ad-a2a6-4829cf8e501a)

Can you pls let me know how can I resolve the above errors and how should I provide the covaraiteSettings object so that I am able to execute my code and obtain the PlpData object?

My session info is as follow:
 
![image](https://github.com/OHDSI/PatientLevelPrediction/assets/81391242/804eaac4-dceb-47e4-895d-d51f8c18de39)

**Comment by egillax** [comment]
The error you're encountering was fixed in v6.3.7 of PLP. It seems you're using v6.3.6. I suggest you update to the latest version (v6.3.8) with:

```R 
remotes::install_github("OHDSI/PatientLevelPrediction")
```

I'm not sure about the hang. From your description I'm missing how you create `cs` and `cohort_covariates`.

**Comment by malihamashkoor123** [comment]
Hi @egillax , 

I have updated the PLP package to the latest version (V6.3.8). However I still get the following error when I execute the getPlpData() function:

![image](https://github.com/user-attachments/assets/4f942f10-ec0d-4d09-91a2-01be39a0c182)

My session info is as follow:

![image](https://github.com/user-attachments/assets/66bb7dca-a2e6-4e94-b2d7-5d8330e7e368)

Additionally, I am creating the cohort covariates by using the createCohortBasedCovariateSettings() in the following way:


![image](https://github.com/user-attachments/assets/7757b14d-45dc-4c4a-863c-428e37168a0b)

**Comment by egillax** [comment]
Hi @malihamashkoor123 ,

I'm struggling a bit to reproduce it. Using `v6.3.8` of PLP and `FeatureExtraction` `v3.5.2` or `v3.6.0` it seems to work for me. But the `minCharacterizationMean` parameter was new in `FeatureExtraction` `v3.5.0`  which the error is pointing at. 

Could you restart your rsession and rerun the code to make sure R is using the correct package versions (nothing old lingering in your workspace). 

If you encounter the error again could you run `traceback()` and share the output here, that way I get more info about the error. Could you also share how you're calling `getPlpData` just to make sure everything's good there.

**Comment by malihamashkoor123** [comment]
Hi @egillax , 

I have restarted the system, the error with the minCharacterizationMean is resolved now. However, I am still unable to fully execute the getPlpData() function. The code is hanging, I have attached herewith a screenshot to show that and also how the getPlpData() function is called:

![image](https://github.com/user-attachments/assets/547c7d4c-5433-43eb-b7a2-1331ecb3bb01)

The output of traceback() is as follow:

![image](https://github.com/user-attachments/assets/ca1917dd-2cfe-4fc9-91bc-e9b3659af75f)

The list of covariates are provided in the following way:
 
![image](https://github.com/user-attachments/assets/3968e9f0-cae6-4a8d-a151-c04e98470d98)

The ‘cs’ variable is obtained from the createCovariateSettings() function. ‘cohort_covariates’ is obtained in the following way:
 
![image](https://github.com/user-attachments/assets/68439d8f-81b3-4d6d-ae2a-5a51c36b88f0)

And custom covariates (‘looCovSet’) is obtained by using the createLooCovariateSettings(). 

My session Info is as follow:

![image](https://github.com/user-attachments/assets/91abf391-9679-48d6-8eec-783630f0ed61)

**Comment by jreps** [comment]
I wonder whether the issue is the way you are combining the covariateSettings.  The cohort_covariates is a list and then you create a list with the standard covariates, the list of cohort covariates and the loo covariates, so I don't think you have a list of covariate settings, you have a list with two settings and a list of settings.  Try this:

# add cs, looCovSet to list 
cohort_covariates[[length(cohort_covariates)+1]] <- cs
cohort_covariates[[length(cohort_covariates)+1]] <- looCovSet 

then 

data <- PatientLevelPrediction::getPlpData(
covariateSettings = cohort_covariates,
...)

**Comment by egillax** [comment]
thanks ! @jreps 

That's exactly the issue. I managed to reproduce it.

**Comment by egillax** [comment]
There is another issue, issue #477 to track better checking of covariateSettings objects passed to PLP. Closing this.
